### ISSUE TITLE
Go modules support

### ISSUE THREAD

**Issue by skovtunenko** [RoseRocket/xerrs#5]
Hello, thank you for the great library!

I'd like to ask you start tagging your releases and publish `go.mod` information.
More details here: [GoWiki: Should I still add a 'go.mod' file if I do not have any dependencies?](https://github.com/golang/go/wiki/Modules#should-i-still-add-a-gomod-file-if-i-do-not-have-any-dependencies)

Thank you in advance!

**Comment by skovtunenko** [comment]
Also, it would be great to see the info about API\code stability in the `README.md` file.

**Comment by anvk** [comment]
@skovtunenko thanks for using it and contributing!

Yeah I will take a look into `go.mod` and code stability in the next few days. Great suggestions!

**Comment by anvk** [comment]
@skovtunenko I added `go.mod`, `go.sum` and `.travis.ci` files to the project. Also there is a new `v1.0.0` tag release. Is it what you were suggesting?

**Comment by skovtunenko** [comment]
Yes, thank you! This issue can be closed then

**Comment by anvk** [comment]
No problem. Thanks for contributing!
